version: '3'
services:
    keep-core:
        build: 
            context: .
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /data:/data
        environment: 
            - CORE_MODE=1
            - OPERATOR_KEY=5957857a88b0ab23b4f2ddd2108e99a114bca0bfe94f0fb5e503a22905e6088f
            - P2P_PORT=3919
            - P2P_PEERS_ARRAY=[]
            - RSK_NODE_URL=wss://testnet.sovryn.app/ws
            - RSK_NODE_PORT=443
        restart: always
        ports:
            - "3919:3919"

    keep-ecdsa:
        build: 
            context: .
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /data:/data
        environment:
            - CORE_MODE=0
            - OPERATOR_KEY=3c53f81b6e3da8a4818a33554bfef1eec57d45c252550c8ac1593de6f0148c46
            - P2P_PORT=3920
            - P2P_PEERS_ARRAY=[]
            - RSK_NODE_URL=wss://testnet.sovryn.app/ws
            - RSK_NODE_PORT=443
        restart: always
        ports:
            - "3920:3920"

    relays:
        network_mode: host
        build:
            context: ./relays/
        environment: 
            - BITCOIN_RPC_ADDRESS=127.0.0.1
            - BITCOIN_RPC_PORT=6061
            - ETH_RCP_ADDRESS=https://testnet.sovryn.app/rpc
            - ETH_RPC_PORT=443
            - CONTRACT_ADDRESS=0xD300c99E5C189a8BdF70Aa8eA8A2a8a681b0D0B6
            - OPERATOR_PRIVATE_KEY=2d61b31f93df83e90e78b61943019f3d03fd9f31901359a0e065a4c896eee23d
            - ETH_CHAIN_ID=31
        restart: always

    keep-dashboard:
        build:
            context: ./keep-core/solidity/dashboard
        ports:
            - "8080:80"
        restart: always

    tbtc-dapp:
        build:
            context: ./tbtc-dapp
        ports:
            - "8081:80"
        restart: always
        