version: '3'
services:
    keep-core:
        build: 
            context: ./keep-core/
            # target: app
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /Users/konrad/Desktop/rumble/test/:/data
        environment: 
            - OPERATOR_ADDRESS=0xd31653ef028dd783001bb78f8784539a44e22718
            - OPERATOR_KEYFILE=/data/eth/keystore/UTC--2021-04-14T10-14-40.670186000Z--d31653ef028dd783001bb78f8784539a44e22718
            - OPERATOR_DATA_DIR=/data/core/data
            - OPERATOR_WALLET_PASSWORD=password
            - P2P_PORT=3919
            - P2P_PEERS_ARRAY=[]
        restart: always
        ports:
            - "3919:3919"

    keep-ecdsa:
        build: 
            context: ./keep-ecdsa/
            # target: app
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /Users/konrad/Desktop/rumble/test/:/data
        environment: 
            - OPERATOR_ADDRESS=0xd31653ef028dd783001bb78f8784539a44e22718
            - OPERATOR_KEYFILE=/data/eth/keystore/UTC--2021-04-14T10-14-40.670186000Z--d31653ef028dd783001bb78f8784539a44e22718
            - OPERATOR_DATA_DIR=/data/ecdsa/data1
            - OPERATOR_WALLET_PASSWORD=password
            - P2P_PORT=3920
            - P2P_PEERS_ARRAY=[]
        restart: always
        ports:
            - "3920:3920"

    relays:
        network_mode: host
        build:
            context: ./relays/
        environment: 
            - BITCOIN_RPC_ADDRESS=127.0.0.1
            - BITCOIN_RPC_PORT=6061
            - ETH_RCP_ADDRESS=https://testnet.sovryn.app/rpc
            - ETH_RPC_PORT=443
            - CONTRACT_ADDRESS=0xD300c99E5C189a8BdF70Aa8eA8A2a8a681b0D0B6
            - OPERATOR_PRIVATE_KEY=2d61b31f93df83e90e78b61943019f3d03fd9f31901359a0e065a4c896eee23d
            - ETH_CHAIN_ID=31
        restart: always
        