version: '3'
services:
    keep-core:
        build: 
            context: ./keep-core/
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /Users/konrad/Desktop/rumble/test/core/data:/data
        environment: 
            - OPERATOR_KEY=5957857a88b0ab23b4f2ddd2108e99a114bca0bfe94f0fb5e503a22905e6088f
            - OPERATOR_KEYFILE_PASSWORD=password
            - P2P_PORT=3919
            - P2P_PEERS_ARRAY=[]
            - RSK_NODE_URL=wss://testnet.sovryn.app/ws
            - RSK_NODE_PORT=443
        restart: always
        ports:
            - "3919:3919"

    keep-ecdsa:
        build: 
            context: ./keep-ecdsa/
            args:
                VERSION: "1.0"
                REVISION: "1"
        volumes:
            - /Users/konrad/Desktop/rumble/test/ecdsa/data1:/var/data
        environment: 
            - OPERATOR_KEY=3c53f81b6e3da8a4818a33554bfef1eec57d45c252550c8ac1593de6f0148c46
            - OPERATOR_KEYFILE_PASSWORD=password
            - P2P_PORT=3920
            - P2P_PEERS_ARRAY=[]
            - RSK_NODE_URL=wss://testnet.sovryn.app/ws
            - RSK_NODE_PORT=443
        restart: always
        ports:
            - "3920:3920"
        